export const CAMPAIGN_FETCH_DATA_SUCCESS = "CAMPAIGN_FETCH_DATA_SUCCESS";
export const SELECTED_CAMPAIGN_UPDATED = "SELECTED_CAMPAIGN_UPDATED";
export const CAMPAIGN_PLAY_FETCH_DATA_SUCCESS = "CAMPAIGN_PLAY_FETCH_DATA_SUCCESS";